# apiVersion: v1
# data:
#   .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJzd2FybmF2YTI4IiwicGFzc3dvcmQiOiJpbG92ZWRvY2tlciIsImVtYWlsIjoic3dhcm5hdmEyOEBnbWFpbC5jb20iLCJhdXRoIjoiYzNkaGNtNWhkbUV5T0RwcGJHOTJaV1J2WTJ0bGNnPT0ifX19
# kind: Secret
# metadata:
#   name: myregistrykey
#   namespace: application
# type: kubernetes.io/dockerconfigjson
# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: app-secrets
#   namespace: application
# data:
#   username: cm9vdA==
#   password: cm9vdA==
#   userpassword: cm9vdA==
# ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app-deployment
  namespace: application
spec:
  selector:
    matchLabels:
      app: java-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  replicas: 2
  template:
    metadata:
      labels:
        app: java-app
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        fsGroup: 1001
      serviceAccountName: application-ns-sa
      containers:
      - name: java-app
        image: swarnava28/java-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 500m
            memory: 200Mi
          requests:
            cpu: 200m
            memory: 100Mi
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 15
          failureThreshold: 3
        env:
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: host

        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: dbName

        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: username

        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: password
