apiVersion: v1
kind: ResourceQuota
metadata:
  name: application-ns-quota
  namespace: application
spec:
  hard:
    pods: "5"
    requests.cpu: "2"
    requests.memory: 1Gi
    limits.cpu: "4"
    limits.memory: 2Gi
