---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: application-role-binding
  namespace: application
subjects:
- kind: ServiceAccount
  name: application-ns-sa
  namespace: application
roleRef:
  kind: Role
  name: application-role
  apiGroup: rbac.authorization.k8s.io
