spring:
  application:
    name: ${SPRING_APPLICATION_NAME:app}
  datasource:
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:dev}
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/challenge?useSSL=false&createDatabaseIfNotExist=true}
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:dev}
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/challenge?useSSL=false&createDatabaseIfNotExist=true}
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: ${ACTUATOR_ENDPOINTS:health,info,prometheus}
