spring:
  application:
    name: ${SPRING_APPLICATION_NAME:app}
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: jdbc:mysql://${DB_HOST}/${DB_NAME}?useSSL=false&createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: jdbc:mysql://${DB_HOST}/${DB_NAME}?useSSL=false&createDatabaseIfNotExist=true
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: ${ACTUATOR_ENDPOINTS:health,info,prometheus}
