apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata:
  # Metadata of the resource kind we are creating
  name: {{ .Values.name }}-svc
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.name }}
  ports:
  - protocol: "TCP"
    port: {{ .Values.image.containerPort }} # The port that the service is running on in the cluster
    targetPort: {{ .Values.image.containerPort }} # The port exposed by the service
  type: NodePort # type of the service.
