---

# apiVersion: networking.k8s.io/v1
# kind: NetworkPolicy
# metadata:
#   name: allow-app-namespace
#   namespace: {{ .Values.namespace }}
# spec:
#   podSelector: {}
#   policyTypes:
#   - Ingress
#   ingress:
#   - from:
#     - namespaceSelector:
#         matchLabels:
#           name: {{ .Values.networkPolicy.allowedNamespace }}
#     # ports:
#     # - protocol: TCP
#     #   port: {{ .Values.image.containerPort }}
