---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.namespace }}-ntp
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
        tier: database
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: {{ .Values.networkPolicy.allowedNamespace }}
    ports:
    - protocol: TCP
      port: {{ .Values.image.containerPort }}

