apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.name }}-pv-claim
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
    tier: database
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.spec.resources.requests.storage }}
