apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.namespace }}-role
  namespace: {{ .Values.namespace }}
rules:
- apiGroups: [ "" ]
  resources:
  - pods
  - services
  - configmaps
  - secrets
  verbs:
  - list
  - get
  - watch
- apiGroups: [ "apps" ]
  resources:
  - deployments
  - statefulsets
  - replicasets
  verbs:
  - list
  - get
  - watch
- apiGroups: [ "batch" ]
  resources:
  - jobs
  - cronjobs
  verbs:
  - list
  - get
  - watch
