apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }} # DNS name
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
    tier: database
spec:
  ports:
  - port: {{ .Values.image.containerPort }}
    targetPort: {{ .Values.image.targetPort }}
  selector:
    app: {{ .Values.name }}
    tier: database
  # clusterIP: None # We Use DNS, Thus ClusterIP is not relevant
