# apiVersion: v1
# kind: Namespace
# metadata:
#   name: database
# ---
# apiVersion: v1
# kind: Namespace
# metadata:
#   name: application
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.namespace }}-ns-sa
  namespace: {{ .Values.namespace }}
automountServiceAccountToken: false
