apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  namespace: database
data:
  host: jdbc:mysql://mysql.database.svc.cluster.local:3306/challenge?useSSL=false&createDatabaseIfNotExist=true
  dbName: challenge
  username: appuser
