apiVersion: v1
kind: Namespace
metadata:
  name: database
---
apiVersion: v1
kind: Namespace
metadata:
  name: application
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: application-ns-sa
  namespace: application
automountServiceAccountToken: false
imagePullSecrets:
- name: myregistrykey
