---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: database-role-binding
  namespace: database
subjects:
- kind: ServiceAccount
  name: database-ns-sa
  namespace: database
roleRef:
  kind: Role
  name: database-role
  apiGroup: rbac.authorization.k8s.io
