apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: database-role
  namespace: database
rules:
- apiGroups: [ "" ]
  resources:
  - pods
  - services
  - configmaps
  - secrets
  verbs:
  - list
  - get
  - watch
- apiGroups: [ "apps" ]
  resources:
  - deployments
  - replicasets
  verbs:
  - list
  - get
  - watch
- apiGroups: [ "batch" ]
  resources:
  - jobs
  - cronjobs
  verbs:
  - list
  - get
  - watch
