# name: Deploy to Kubernetes

# on:
#   push:
#     branches:
#       - main
# jobs:
#     deploy:
#       name: Deploy to Kubernetes
#       runs-on: ubuntu-latest
#       steps:
#       - name: Checkout code
#         uses: actions/checkout@v2
#       - name: Create kubeconfig
#         run: |
#           mkdir ${HOME}/.kube
#           echo ${{ secrets.KUBE_CONFIG }} | base64 --decode > ${HOME}/.kube/config
#           cat ${HOME}/.kube/config
#       - name: Use context
#         run: kubectl get nodes

name: CI pipleine creation for Spring Boot application

# This workflow is triggered whenever a new PR is created on the mentioned branch
on:
  push:
    branches:
      - main

env:
  DB_DATABASE: crewmeister
jobs:
    Deploy:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4
        name: Checkout the crewmeister repository          

      - name: Prerequisite 1 - Set up JDK 17
        uses: actions/setup-java@v4
        with:
            java-version: '17'
            distribution: 'temurin'
            cache: 'maven