name: CI pipleine
on:
  push:
    branches:
      - main

env:
  DB_DATABASE: crewmeiste
jobs:
    Build-and-Push:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4
        name: Checkout the crewmeister repository          
      - name: Prerequisite 1 - Set up JDK 17
        uses: actions/setup-java@v4
        with:
            java-version: '17'
            distribution: 'temurin'
            cache: 'maven'
      - name: Prerequisite 2 - Build project crewmeister with Maven
        run: ./mvnw clean package -DskipTests 

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: swarnava28
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
            context: .
            push: true
            tags: swarnava28/java-app:${GITHUB_SHA::6}
    # Deploy:
    #   uses: ./.github/workflows/cd.yml
