apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "crewmeister.fullname" . }}
  labels:
    {{- include "crewmeister.labels" . | nindent 4 }}
spec:
  imagePullSecrets:
  - name: crewmeister-secret
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "crewmeister.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "crewmeister.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "crewmeister.serviceAccountName" . }}
      imagePullSecrets:
        {{- if .Values.imagePullSecrets }}
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
        {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP